#!/bin/bash
set -euo pipefail
arch="$1"  # amd64, arm64, etc.
server="$2"
test -n "$arch"
test -n "$server"

service=ticketsummary

echo "Deploying to $server ($arch)..."
set -x
now=$(date '+%Y-%m-%d-T%H%M%S')

GOOS=linux GOARCH=$arch go build -o "/tmp/$service-linux-$arch-$now" .
scp "/tmp/$service-linux-$arch-$now" "$server:~/"
ssh $server "sudo install -m 755 -o root -g root ~/$service-linux-$arch-$now /srv/$service/bin/$service"
